### ISSUE TITLE
the fastcgi process died?

### ISSUE THREAD

**Issue by vlahde** [mkoppanen/php-zmq#104]
Hi you guys!

I have a working ratchet/php-zmq pusher service on my own server which is Debian Gnu/Linux 7.0 / lighttpd. In my work I have CentOS 6.4 / Lighttpd. There is a php script rc.php, which pushes the received message to the socket. 

Now the problem is that while both servers run the server script just fine, the pusher script returns 500 - Internal Server Error on the CentOS system when run via lighttpd. When I run the script as the same user which uses lighttpd thru command line, it works ok.

In the error logs there is these lines when tried to run rc.php on lighttpd:

2013-10-11 16:00:33: (mod_fastcgi.c.2568) unexpected end-of-file (perhaps the fastcgi process died): pid: 17977 socket: unix:/var/run/lighttpd/lighttpd-fastcgi1-php.socket-0 

2013-10-11 16:00:33: (mod_fastcgi.c.3356) response not received, request sent: 824 on socket: unix:/var/run/lighttpd/lighttpd-fastcgi1-php.socket-0 for /rc.php?, closing connection

So it seems light rights issue. I have chmod the /var/run/lighttpd/ folder to 777 and the sockets within too but with no prevail.

Here is my service code: 

     //send message to ZMQ
     $context = new ZMQContext();
     $socket = $context->getSocket(ZMQ::SOCKET_PUSH);
     $socket->connect("tcp://127.0.0.1:5555");
     $socket->send($msg);

I have tried to run it on apache too but it has the same result. I am really stuck with this issue. Thanks for reading this and helping me out or to forward me somewhere that could assist me further. 

Have a great weekend!

**Comment by mkoppanen** [comment]
No feedback provided
