### ISSUE TITLE
Sending data fails in a thread

### ISSUE THREAD

**Issue by rinu** [mkoppanen/php-zmq#126]
Test script:
```php
<?php
class MyThread extends Thread {
	public function run() {
		$socket = new ZMQSocket(new ZMQContext(), ZMQ::SOCKET_PUSH);
		$socket->connect("tcp://127.0.0.1:5666");
		$socket->send("stuff", ZMQ::MODE_DONTWAIT);
	}
}

$socket = new ZMQSocket(new ZMQContext(), ZMQ::SOCKET_PULL);
$socket->bind("tcp://127.0.0.1:5666");

$thread = new MyThread();
$thread->start();
$thread->join();

echo "Result: " . $socket->recv() . PHP_EOL;
?>
```

$socket->recv() will hang forever. Expected it to get the message sent in a thread.

The problem is only on Windows. Cannot reproduce the bug on my Ubuntu 13.10.
My Windows 7 setup:
Latest pthreads (2.0.4)
Latest WampServer (with PHP 5.4.16)
Latest zmq from http://pecl.php.net/package/zmq/1.1.2/windows

Sidenote: would be nice if the PHP binding supported inproc.

**Comment by mkoppanen** [comment]
Closing this as there has been improvements to support pthreads extension.
