### ISSUE TITLE
Unexpected behaviour with INPROC and ZMQ::SOCKOPT_FD

### ISSUE THREAD

**Issue by Majeh** [mkoppanen/php-zmq#130]
Update:
PHP version: 5.6.4
ZeroMQ version: 4.1.0
PHP-ZMQ extension: https://github.com/mkoppanen/php-zmq/tree/feature-global-context
ZMQ extension is built from the mentioned branch

First off - I'd like to apologize if I'm asking the question at the wrong place.

I'm using PHP pthreads extension and libev PHP extension together with PHP ZMQ extension to perform certain work and everything works ok, except with one little detail.

I'm using INPROC transport to distribute work from main context to worker threads and it works great, I'm able to read the message using `ZMQPoll()` and react when events are present. However, I'd like to be able to use the event loop instead of `ZMQPoll()`.

The problem is that event loop doesn't register that an event occurred on `\ZMQ::SOCKOPT_FD` when transport is INPROC and I can't read the message that was sent - causing the whole php script to idle as if nothing happened. When transport is TCP or IPC then it works just fine, which leads me to opening this issue / question - is there anything special going on with the file descriptor when the transport is INPROC? I wasn't able to find anything in ZeroMQ documents that would hint that INPROC is hugely different to other transports. Note: I definitely bound to INPROC endpoint before connecting (main context binds, threads connect, main context pushes while threads pull).

**Comment by kernelguy** [comment]
I believe I am seeing the same issue.
I'm using reactphp with react-zmq for a smaller web service. When clients connect through websocket they subscribe to data from a common publisher run on timer events.
When the clients to connect to "tcp://127.0.0.1" it works fine, but if I try to use "inproc://publisher" nothing happens.
The timer is still running and updates are published, but nothing are received by the subscribers.

**Comment by phuedx** [comment]
@Majeh, @kernelguy: could you tell update your bug reports with the version of PHP and php-zmq that you're using?

**Comment by Majeh** [comment]
@phuedx  - I've updated the info with version numbers, but I'd just like to mention that I've noticed the problem with various older versions of PHP and various older versions of the extension itself. I'm almost sure that it's not PHP or extension's fault, but I've no time or resources to go dig up the cause. If you've got any idea on how to approach locating the bug, that would be awesome. Thanks for your time :+1:

**Comment by phuedx** [comment]
@Majeh I sorta suspected but it's always useful to have a starting point. The last thing I want to do is respond with "Wellp… it works in the latest version of PHP and php-zmq!"

**Comment by Majeh** [comment]
@phuedx  - if you replied with that, I'd be more than happy to just pull the latest stuff and rebuild it :) 

I'll put together some reproduction code during next 24 hours.

**Comment by phuedx** [comment]
I took the liberty of creating an environment to reproduce this bug (see [phuedx/php-zmq-issue-130](https://github.com/phuedx/php-zmq-issue-130).

I'll make sure I document my findings both here and there.

**Comment by phuedx** [comment]
Something that caught my eye while I was reading the [`zmq_getsockopt(3)` documentation][0]:

> The ability to read from the returned file descriptor does not necessarily indicate that messages are available to be read from, or can be written to, the underlying socket; applications must retrieve the actual event state with a subsequent retrieval of the ZMQ_EVENTS option.

[0]: http://api.zeromq.org/master:zmq-getsockopt

**Comment by phuedx** [comment]
@Majeh: have you been able to write a script that we can use to reproduce the bug?

**Comment by Majeh** [comment]
@phuedx sorry for the delay, I'm working on it now (trying to figure out whether I can provide an example without LibEV).

**Comment by phuedx** [comment]
@Majeh Thanks in advance.

@kernelguy Any more detail you could provide about the issue would be greatly appreciated. If I'm reading your summary correctly, then you're handling sending to multiple websocket clients and reading from a single ØMQ socket in a single event loop; when you read something from the ØMQ socket then you send to multiple clients? What's publishing the data in your system?

**Comment by Majeh** [comment]
Gist: [check it here](https://gist.github.com/Majeh/fcf647c231b028ec663e)

Requirements: [PHP LibEV extension](https://github.com/m4rw3r/php-libev)

How to run: execute from CLI, `php the_gist_file.php`.

What you should see when it works: 
```bash
Sending message

Message received!Array
(
    [0] => hello
    [1] => 1424255051
)

Sending message

Message received!Array
(
    [0] => hello
    [1] => 1424255053
)

```

What you see when it doesn't work: 
```bash
Sending message
Sending message
```

Problem description: in the gist, you can see that there's an endpoint using TCP transport. When executed using that transport, messages are being received. When swapping out for `inproc` endpoint, messages aren't received.

PHP version: 
```
php -v
PHP 5.6.4 (cli) (built: Feb 10 2015 11:27:26) (DEBUG)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
```

libzmq version: 
```
pkg-config libzmq --modversion
4.1.0
```

I didn't try with libzmq 4.2.0 (yet).

The gist example is a simple one. The "big" idea was to use zmq for inter-thread communication (using PHP's pthreads extension to create threads in PHP). I used the branch global-context of php-zmq extension obtain the thread-safe context. I can confirm that everything works fine from pthreads POV, every zmq transport is correctly utilized save the `inproc` when used via the LibEV.

If I use ZMQPoll() instead of LibEV then `inproc` transport works correctly and I can send / receive messages.

**Comment by kernelguy** [comment]
@phuedx Sorry for the much delayed answer
My system and file versions are:
```
OS: Ubuntu 14.04.1 LTS
PHP: 5.5.9-1ubuntu4.6
ZMQ: (zeromq3) 4.0.4+dfsg-2
PHP-ZMQ: 1.1.2
```

I use [React-PHP](https://github.com/reactphp/react), which I believe is using libevent, and [React-ZMQ](https://github.com/reactphp/zmq).

My usage is pretty much like the example given by @Majeh:
A timer based publisher writes events to a ZMQ::PUB socket and multiple websocket clients listen to a ZMQ:SUB socket.
Publisher:
```php
        $this->context = new \React\ZMQ\Context($this->getLoop());
        $this->publisher = $this->context->getSocket(\ZMQ::SOCKET_PUB);
        $this->publisher->bind('tcp://127.0.0.1:5555');
//        $this->publisher->bind('inproc://publisher');
...
        $this->publisher->send($msg);
```
Subscribers:
```php
        $this->subscriber = ControlApp::get()->getContext()->getSocket(\ZMQ::SOCKET_SUB);
        $this->subscriber->connect('tcp://127.0.0.1:5555');
//        $this->subscriber->connect('inproc://publisher');
        $this->subscriber->on('message', array($this, 'on0MQMessage'));
```
If I change the connect and bind calls to use the commented inproc lines, nothing is ever received.
I dont know if it is an error in php-zmq or the react-zmq wrapper.

**Comment by Majeh** [comment]
I managed to google-fu [this link](http://lists.zeromq.org/pipermail/zeromq-dev/2014-January/024545.html) which comments on similar behavior. 

What it says is to first connect, then bind and in that case inproc with events+fd works. Using my example, I managed to make it work by swapping the connect to be first and bind to be second.

**Comment by kernelguy** [comment]
I just tried to add a dummy subscriber that connects before the publisher binds.
It does not work for me: The dummy subscriber connected before the bind call or any client subscriber that connects afterwards, does not receive any messages.

As I read the dev link, there is no point in me pursuing this issue more. My subscribers are connecting asynchrounously so I can newer connect before the bind call in my application.
It works fine with the tcp connections, I was just not satisfied with having to use a bunch of tcp connections within the same program.

I'm OK with closing this issue. I guess I will have to look into the React-ZMQ code to figure out why the connect-then-bind approax does not work for me.

**Comment by Majeh** [comment]
There are many older issues (from 2012.) where people reported the same problem, but they had to bind first, connect second. At some point, it got reversed - connect first, bind second (I have no clue why). Also, I have the same problem as you @kernelguy  - I have workers that can die or be killed and new ones need to connect. The solution I posted absolutely doesn't work for me in the use scenario mentioned. I guess we'll have to bug libzmq devs to see how to get around this issue..

**Comment by phuedx** [comment]
@Majeh @kernelguy: The bind-before-connect tests in [test_inproc_connect.cpp][0] seem to suggest that it only works for the exclusive pair pattern.

@kernelguy:

> It works fine with the tcp connections, I was just not satisfied with having to use a bunch of tcp connections within the same program.

Bind-before-connect with IPC works fine for me. Sure, you'll have a temporary file laying around but it might be better than a bunch of TCP connections.

[0]: https://github.com/zeromq/libzmq/blob/master/tests/test_inproc_connect.cpp

**Comment by phuedx** [comment]
@Majeh @kernelguy: So, I guess the resolution is: clearer documentation about the inproc transport?

**Comment by Majeh** [comment]
@phuedx - yes, as far as I'm concerned, I think we can close the issue. @kernelguy - waiting for your response :)

**Comment by mkoppanen** [comment]
Closing issue as there is no feedback
