### ISSUE TITLE
Fatal error: Class 'ZMQ' not found in \index.php

### ISSUE THREAD

**Issue by Qws** [mkoppanen/php-zmq#142]
I've just installed ZMQ, followed the tutorial for Windows, everythings works. Except the fact that I cannot create object of ZMQContext because ZMQ class in the parameter is not defined.

  $context = new ZMQContext(1);
  $publisher = new ZMQSocket($context, ZMQ::SOCKET_PUB); //ZMQ is not defined.

How can I initialise it without ZMQ being defined?

**Comment by phuedx** [comment]
Try:

```php
$context = new ZMQContext(1);
$publisher = new ZMQSocket($context, ZMQSocket::SOCKET_PUB);
```

See the [`ZMQSocket` class in api.php](https://github.com/mkoppanen/php-zmq/blob/master/api.php#L44) for the list of `SOCKET_*` constants.

**Comment by phuedx** [comment]
Y'know what? I was wrong. The `SOCKET_*` constants are definitely defined on the `ZMQ` class.

So…

Which version of PHP and php-zmq are you using?

**Comment by mkoppanen** [comment]
No feedback
