### ISSUE TITLE
OpenSuse 13.2

### ISSUE THREAD

**Issue by UXMichael** [mkoppanen/php-zmq#143]
Build on OpenSuse 13.2 works, but zmq throws memory faults. ( libzmq 4.0.5 ).

Maybe an idea ?

**Comment by phuedx** [comment]
@UXMichael: do you have a small script that'll demonstrate the bug?

**Comment by phuedx** [comment]
Also, `php-zmq` master?

**Comment by UXMichael** [comment]
Last Revision ( 505 ) . A small script i havent. 
Thats the dump
*** Error in `php': double free or corruption (out): 0x00007fbaad805020 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7283f)[0x7fbaaa08a83f]
/lib64/libc.so.6(+0x780ae)[0x7fbaaa0900ae]
/lib64/libc.so.6(+0x78db6)[0x7fbaaa090db6]
php(+0x46c71e)[0x7fbaabfb371e]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fbaaa039b05]
php(+0x46c919)[0x7fbaabfb3919]
======= Memory map: ========
7fba90000000-7fba90021000 rw-p 00000000 00:00 0 
7fba90021000-7fba94000000 ---p 00000000 00:00 0 
7fba98000000-7fba98021000 rw-p 00000000 00:00 0 
7fba98021000-7fba9c000000 ---p 00000000 00:00 0 
7fba9c85e000-7fba9c893000 r--s 00000000 00:11 13930                      /run/nscd/dbZycgoT (deleted)
7fba9c893000-7fba9c894000 ---p 00000000 00:00 0 
7fba9c894000-7fba9d094000 rw-p 00000000 00:00 0 
7fba9d094000-7fba9d095000 ---p 00000000 00:00 0 
7fba9d095000-7fba9d895000 rw-p 00000000 00:00 0 
7fba9d895000-7fba9d8a0000 r-xp 00000000 08:02 15990986                   /lib64/libnss_files-2.19.so
7fba9d8a0000-7fba9da9f000 ---p 0000b000 08:02 15990986                   /lib64/libnss_files-2.19.so
7fba9da9f000-7fba9daa0000 r--p 0000a000 08:02 15990986                   /lib64/libnss_files-2.19.so
7fba9daa0000-7fba9daa1000 rw-p 0000b000 08:02 15990986                   /lib64/libnss_files-2.19.so
7fba9db4d000-7fba9dc37000 r-xp 00000000 08:02 9831414                    /usr/lib64/libstdc++.so.6.0.19
7fba9dc37000-7fba9de36000 ---p 000ea000 08:02 9831414                    /usr/lib64/libstdc++.so.6.0.19
7fba9de36000-7fba9de3e000 r--p 000e9000 08:02 9831414                    /usr/lib64/libstdc++.so.6.0.19
7fba9de3e000-7fba9de40000 rw-p 000f1000 08:02 9831414                    /usr/lib64/libstdc++.so.6.0.19
7fba9de40000-7fba9de55000 rw-p 00000000 00:00 0 
7fba9de55000-7fba9de5c000 r-xp 00000000 08:02 15991002                   /lib64/librt-2.19.so
7fba9de5c000-7fba9e05b000 ---p 00007000 08:02 15991002                   /lib64/librt-2.19.so
7fba9e05b000-7fba9e05c000 r--p 00006000 08:02 15991002                   /lib64/librt-2.19.so
7fba9e05c000-7fba9e05d000 rw-p 00007000 08:02 15991002                   /lib64/librt-2.19.so
7fbaa36c0000-7fbaa36d6000 r-xp 00000000 08:02 15990819                   /lib64/libgcc_s.so.1
7fbaa36d6000-7fbaa38d5000 ---p 00016000 08:02 15990819                   /lib64/libgcc_s.so.1
7fbaa38d5000-7fbaa38d6000 r--p 00015000 08:02 15990819                   /lib64/libgcc_s.so.1
7fbaa38d6000-7fbaa38d7000 rw-p 00016000 08:02 15990819                   /lib64/libgcc_s.so.1
7fbaa9bd5000-7fbaa9bfa000 r-xp 00000000 08:02 9831241                    /usr/lib64/liblzma.so.5.0.7
7fbaa9bfa000-7fbaa9df9000 ---p 00025000 08:02 9831241                    /usr/lib64/liblzma.so.5.0.7
7fbaa9df9000-7fbaa9dfa000 r--p 00024000 08:02 9831241                    /usr/lib64/liblzma.so.5.0.7
7fbaa9dfa000-7fbaa9dfb000 rw-p 00025000 08:02 9831241                    /usr/lib64/liblzma.so.5.0.7
7fbaa9dfb000-7fbaa9e13000 r-xp 00000000 08:02 15990949                   /lib64/libpthread-2.19.so
7fbaa9e13000-7fbaaa012000 ---p 00018000 08:02 15990949                   /lib64/libpthread-2.19.so
7fbaaa012000-7fbaaa013000 r--p 00017000 08:02 15990949                   /lib64/libpthread-2.19.so
7fbaaa013000-7fbaaa014000 rw-p 00018000 08:02 15990949                   /lib64/libpthread-2.19.so
7fbaaa014000-7fbaaa018000 rw-p 00000000 00:00 0 
7fbaaa018000-7fbaaa1b6000 r-xp 00000000 08:02 15990985                   /lib64/libc-2.19.so
7fbaaa1b6000-7fbaaa3b5000 ---p 0019e000 08:02 15990985                   /lib64/libc-2.19.so
7fbaaa3b5000-7fbaaa3b9000 r--p 0019d000 08:02 15990985                   /lib64/libc-2.19.so
7fbaaa3b9000-7fbaaa3bb000 rw-p 001a1000 08:02 15990985                   /lib64/libc-2.19.so
7fbaaa3bb000-7fbaaa3bf000 rw-p 00000000 00:00 0 
7fbaaa3bf000-7fbaaa5b6000 r-xp 00000000 08:02 15991024                   /lib64/libcrypto.so.1.0.0
7fbaaa5b6000-7fbaaa7b6000 ---p 001f7000 08:02 15991024                   /lib64/libcrypto.so.1.0.0
7fbaaa7b6000-7fbaaa7d1000 r--p 001f7000 08:02 15991024                   /lib64/libcrypto.so.1.0.0
7fbaaa7d1000-7fbaaa7de000 rw-p 00212000 08:02 15991024                   /lib64/libcrypto.so.1.0.0
7fbaaa7de000-7fbaaa7e2000 rw-p 00000000 00:00 0 
7fbaaa7e2000-7fbaaa941000 r-xp 00000000 08:02 9831256                    /usr/lib64/libxml2.so.2.9.1
7fbaaa941000-7fbaaab41000 ---p 0015f000 08:02 9831256                    /usr/lib64/libxml2.so.2.9.1
7fbaaab41000-7fbaaab49000 r--p 0015f000 08:02 9831256                    /usr/lib64/libxml2.so.2.9.1
7fbaaab49000-7fbaaab4b000 rw-p 00167000 08:02 9831256                    /usr/lib64/libxml2.so.2.9.1
7fbaaab4b000-7fbaaab4d000 rw-p 00000000 00:00 0 
7fbaaab4d000-7fbaaab62000 r-xp 00000000 08:02 15990871                   /lib64/libz.so.1.2.8
7fbaaab62000-7fbaaad61000 ---p 00015000 08:02 15990871                   /lib64/libz.so.1.2.8
7fbaaad61000-7fbaaad62000 r--p 00014000 08:02 15990871                   /lib64/libz.so.1.2.8
7fbaaad62000-7fbaaad63000 rw-p 00015000 08:02 15990871                   /lib64/libz.so.1.2.8
7fbaaad63000-7fbaaad66000 r-xp 00000000 08:02 15990937                   /lib64/libdl-2.19.so
7fbaaad66000-7fbaaaf65000 ---p 00003000 08:02 15990937                   /lib64/libdl-2.19.so
7fbaaaf65000-7fbaaaf66000 r--p 00002000 08:02 15990937                   /lib64/libdl-2.19.so
7fbaaaf66000-7fbaaaf67000 rw-p 00003000 08:02 15990937                   /lib64/libdl-2.19.so
7fbaaaf67000-7fbaab067000 r-xp 00000000 08:02 15990945                   /lib64/libm-2.19.so
7fbaab067000-7fbaab266000 ---p 00100000 08:02 15990945                   /lib64/libm-2.19.so
7fbaab266000-7fbaab267000 r--p 000ff000 08:02 15990945                   /lib64/libm-2.19.so
7fbaab267000-7fbaab268000 rw-p 00100000 08:02 15990945                   /lib64/libm-2.19.so
7fbaab268000-7fbaab2d1000 r-xp 00000000 08:02 9832657                    /usr/lib64/libpcre.so.1.2.3
7fbaab2d1000-7fbaab4d0000 ---p 00069000 08:02 9832657                    /usr/lib64/libpcre.so.1.2.3
7fbaab4d0000-7fbaab4d1000 r--p 00068000 08:02 9832657                    /usr/lib64/libpcre.so.1.2.3
7fbaab4d1000-7fbaab4d2000 rw-p 00069000 08:02 9832657                    /usr/lib64/libpcre.so.1.2.3
7fbaab4d2000-7fbaab4e6000 r-xp 00000000 08:02 15990989                   /lib64/libresolv-2.19.so
7fbaab4e6000-7fbaab6e5000 ---p 00014000 08:02 15990989                   /lib64/libresolv-2.19.so
7fbaab6e5000-7fbaab6e6000 r--p 00013000 08:02 15990989                   /lib64/libresolv-2.19.so
7fbaab6e6000-7fbaab6e7000 rw-p 00014000 08:02 15990989                   /lib64/libresolv-2.19.so
7fbaab6e7000-7fbaab6e9000 rw-p 00000000 00:00 0 
7fbaab6e9000-7fbaab6f5000 r-xp 00000000 08:02 15990936                   /lib64/libcrypt-2.19.so
7fbaab6f5000-7fbaab8f4000 ---p 0000c000 08:02 15990936                   /lib64/libcrypt-2.19.so
7fbaab8f4000-7fbaab8f5000 r--p 0000b000 08:02 15990936                   /lib64/libcrypt-2.19.so
7fbaab8f5000-7fbaab8f6000 rw-p 0000c000 08:02 15990936                   /lib64/libcrypt-2.19.so
7fbaab8f6000-7fbaab924000 rw-p 00000000 00:00 0 
7fbaab924000-7fbaab944000 r-xp 00000000 08:02 15990874                   /lib64/ld-2.19.so
7fbaab991000-7fbaab9d0000 r--p 00000000 08:02 11274091                   /usr/lib/locale/de_DE.utf8/LC_CTYPE
7fbaabb12000-7fbaabb19000 rw-p 00000000 00:00 0 
7fbaabb3b000-7fbaabb3c000 rw-p 00000000 00:00 0 
7fbaabb3c000-7fbaabb43000 r--s 00000000 08:02 9966686                    /usr/lib64/gconv/gconv-modules.cache
7fbaabb43000-7fbaabb44000 rw-p 00000000 00:00 0 
7fbaabb44000-7fbaabb45000 r--p 00020000 08:02 15990874                   /lib64/ld-2.19.so
7fbaabb45000-7fbaabb46000 rw-p 00021000 08:02 15990874                   /lib64/ld-2.19.so
7fbaabb46000-7fbaabb47000 rw-p 00000000 00:00 0 
7fbaabb47000-7fbaac2d2000 r-xp 00000000 08:02 9843127                    /usr/bin/php
7fbaac4d2000-7fbaac691000 r--p 0078b000 08:02 9843127                    /usr/bin/php
7fbaac691000-7fbaac697000 rw-p 0094a000 08:02 9843127                    /usr/bin/php
7fbaac697000-7fbaac6a2000 rw-p 00000000 00:00 0 
7fbaad803000-7fbaadaf4000 rw-p 00000000 00:00 0                          [heap]
7fff6a59a000-7fff6a5bb000 rw-p 00000000 00:00 0                          [stack]
7fff6a5fc000-7fff6a5fe000 r-xp 00000000 00:00 0                          [vdso]
7fff6a5fe000-7fff6a600000 r--p 00000000 00:00 0                          [vvar]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by mkoppanen** [comment]
Please reopen if you can reproduce with latest
