### ISSUE TITLE
Invalid links to PHP reference manual

### ISSUE THREAD

**Issue by jakubmacek** [mkoppanen/php-zmq#144]
Apparently, the redirection at php.zero.mq subdomain has been discontinued some time ago (I guess end of 2013), but the official page at http://zeromq.org/bindings:php and doc at https://github.com/mkoppanen/php-zmq/wiki/API-docs both reference this page instead of the new http://php.net/zmq.

**Comment by phuedx** [comment]
@jakubmacek I've updated the links on both of those pages. Could you confirm the changes and close the issue if you're happy?

**Comment by jakubmacek** [comment]
Thank you.
