### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by martinslmn** [mkoppanen/php-zmq#145]
I am trying to install this on Ubuntu-14.04 and PHP 5.2.10. I did see the previous solution to upgrade PHP. But I could not do that. Is there any other way to install this?

I am getting the following error.

/bin/bash /root/php-zmq/libtool --mode=compile cc  -I. -I/root/php-zmq -DPHP_ATOM_INC -I/root/php-zmq/include -I/root/php-zmq/main -I/root/php-zmq -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /root/php-zmq/zmq.c -o zmq.lo
libtool: compile:  cc -I. -I/root/php-zmq -DPHP_ATOM_INC -I/root/php-zmq/include -I/root/php-zmq/main -I/root/php-zmq -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /root/php-zmq/zmq.c  -fPIC -DPIC -o .libs/zmq.o
/root/php-zmq/zmq.c: In function 'php_zmq_printable_func':
/root/php-zmq/zmq.c:471:9: error: 'zend_fcall_info' has no member named 'object_ptr'
  if (fci->object_ptr) {
         ^
In file included from /usr/include/php5/Zend/zend.h:684:0,
                 from /usr/include/php5/main/php.h:34,
                 from /root/php-zmq/php_zmq.h:45,
                 from /root/php-zmq/zmq.c:31:
/root/php-zmq/zmq.c:472:49: error: 'zend_fcall_info' has no member named 'object_ptr'
   spprintf (&buffer, 0, "%s::%s", Z_OBJCE_P (fci->object_ptr)->name, fci_cache->function_handler->common.function_name);
                                                 ^
/usr/include/php5/Zend/zend_operators.h:377:48: note: in definition of macro 'Z_OBJCE'
 #define Z_OBJCE(zval)   zend_get_class_entry(&(zval) TSRMLS_CC)
                                                ^
/root/php-zmq/zmq.c:472:35: note: in expansion of macro 'Z_OBJCE_P'
   spprintf (&buffer, 0, "%s::%s", Z_OBJCE_P (fci->object_ptr)->name, fci_cache->function_handler->common.function_name);
                                   ^
In file included from /usr/include/php5/main/php.h:38:0,
                 from /root/php-zmq/php_zmq.h:45,
                 from /root/php-zmq/zmq.c:31:
/root/php-zmq/zmq.c: In function 'php_zmq_connect_callback':
/usr/include/php5/Zend/zend_API.h:465:13: warning: initialization discards 'const' qualifier from pointer target type [enabled by default]
   char *__s=(s);     \
             ^
/root/php-zmq/zmq.c:493:3: note: in expansion of macro 'ZVAL_STRING'
   ZVAL_STRING(pid_z, persistent_id, 1);
   ^
/root/php-zmq/zmq.c: In function 'zim_zmqpoll_add':
/root/php-zmq/zmq.c:1230:3: warning: passing argument 2 of 'zend_throw_exception' discards 'const' qualifier from pointer target type [enabled by default]
   zend_throw_exception(php_zmq_poll_exception_sc_entry, message, PHP_ZMQ_INTERNAL_ERROR TSRMLS_CC);
   ^
In file included from /root/php-zmq/php_zmq_private.h:35:0,
                 from /root/php-zmq/zmq.c:32:
/usr/include/php5/Zend/zend_exceptions.h:39:17: note: expected 'char *' but argument is of type 'const char *'
 ZEND_API zval * zend_throw_exception(zend_class_entry *exception_ce, char *message, long code TSRMLS_DC);
                 ^
/root/php-zmq/zmq.c: In function 's_clear_device_callback':
/root/php-zmq/zmq.c:1440:14: error: 'zend_fcall_info' has no member named 'object_ptr'
   if (cb->fci.object_ptr != NULL) {
              ^
In file included from /usr/include/php5/Zend/zend.h:685:0,
                 from /usr/include/php5/main/php.h:34,
                 from /root/php-zmq/php_zmq.h:45,
                 from /root/php-zmq/zmq.c:31:
/root/php-zmq/zmq.c:1441:26: error: 'zend_fcall_info' has no member named 'object_ptr'
    zval_ptr_dtor(&cb->fci.object_ptr);
                          ^
/usr/include/php5/Zend/zend_variables.h:55:49: note: in definition of macro 'zval_ptr_dtor'
 #define zval_ptr_dtor(zval_ptr) _zval_ptr_dtor((zval_ptr) ZEND_FILE_LINE_CC)
                                                 ^
/root/php-zmq/zmq.c: In function 's_init_device_callback':
/root/php-zmq/zmq.c:1525:9: error: 'zend_fcall_info' has no member named 'object_ptr'
  if (fci->object_ptr) {
         ^
In file included from /root/php-zmq/zmq.c:32:0:
/root/php-zmq/zmq.c:1526:18: error: 'zend_fcall_info' has no member named 'object_ptr'
   Z_ADDREF_P (fci->object_ptr);
                  ^
/root/php-zmq/php_zmq_private.h:191:26: note: in definition of macro 'Z_ADDREF_P'
 # define Z_ADDREF_P(pz) (pz)->refcount++
                          ^
/root/php-zmq/zmq.c: In function 'zim_zmqdevice_setidlecallback':
/root/php-zmq/zmq.c:1545:36: error: 'E_DEPRECATED' undeclared (first use in this function)
   php_error_docref(NULL TSRMLS_CC, E_DEPRECATED, "The signature for setIdleCallback has changed, please update your code");
                                    ^
/root/php-zmq/zmq.c:1545:36: note: each undeclared identifier is reported only once for each function it appears in
make: *** [zmq.lo] Error 1

**Comment by phuedx** [comment]
PHP 5.2 is an unsupported branch (EOL was 6th Jan 2011). @mkoppanen: should php-zmq support PHP 5.2?

Regardless, the README should be updated to include the list of supported PHP versions.

**Comment by mkoppanen** [comment]
There is no reason to support PHP 5.2 anymore. I am willing to review a PR that reinstates the support cleanly, but at the moment I really don't have time to spend on support end of life branch.

**Comment by phuedx** [comment]
@mkoppanen I guess this should issue should be closed then.
