### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226-zts/zmq.so' - /usr/lib/php5/20131226-zts/zmq.so

### ISSUE THREAD

**Issue by FourmiCrobe** [mkoppanen/php-zmq#147]
Hi there, 

I've upgrade to PHP 5.6 (ZTS) with Dotdeb Wheezy package. 
Then i've reinstall PHP and zmq pecl package, and i get this message 

`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226-zts/zmq.so' - /usr/lib/php5/20131226-zts/zmq.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Fatal error:  Class 'ZMQContext' not found`

It's seems that extension dir has change for PHP 5.6 ZTS Dotdeb build. I founded zmq.so extension in /usr/lib/php5/20100525+lfs/zmq.so 

So, i've create a symbolic link from /usr/lib/php5/20100525+lfs/zmq.so to /usr/lib/php5/20131226-zts/zmq.so' . 

Then i get now this message : 
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226-zts/zmq.so' - /usr/lib/php5/20131226-zts/zmq.so: undefined symbol: executor_globals in Unknown on line 0
PHP Fatal error:  Class 'ZMQContext' not found`

I've also git clone and build the package, but i get the same messages.

Have you got an idea ? Am i doing wrong ? 

Thanks
Cédric

**Comment by Majeh** [comment]
You can't link a library built for a different version and expect it to work. You have PHP 5.6 now and you should rebuild the extension from ground up. 

Steps you need to execute: 

```bash
git clone https://github.com/mkoppanen/php-zmq.git
cd php-zmq/
phpize
./configure
make
make install
```

Read what the console says so you can see where it installs the extension. After that you just need to enable the extension in php.ini.

**Comment by phuedx** [comment]
Ping @FourmiCrobe. Could you please close this issue if you've successfully reinstalled the extension.

**Comment by mkoppanen** [comment]
Closing
