### ISSUE TITLE
PHP Warning:  PHP Startup: zmq: Unable to initialize module Module compiled with module API=20100525 PHP    compiled with module API=20131226 These options need to match  in Unknown on line 0

### ISSUE THREAD

**Issue by kirensiva** [mkoppanen/php-zmq#148]
PHP Warning:  PHP Startup: zmq: Unable to initialize module
Module compiled with module API=20100525
PHP    compiled with module API=20131226
These options need to match
 in Unknown on line 0

Getting this warning after installing the zmq extension. The installed zmq.so file is in /usr/lib/php/extensions/no-debug-non-zts-20100525/. I am using XAMPP for OS X 5.6.3-0 having PHP Version 5.6.3. and its extension directory is (as shown in phpinfo)
extension_dir =  /Applications/XAMPP/xamppfiles/lib/php/extensions/no-debug-non-zts-20131226

What should I do for get it work. :( Please help me

**Comment by Majeh** [comment]
Please take a look at #147. You need to recompile the php-zmq extension for the PHP version you are using. I also included the steps so you can basically copy paste them.

**Comment by kirensiva** [comment]
I followed the steps but again same error. I think when I git clone https://github.com/mkoppanen/php-zmq.git it clones the source for PHP API=20100525 But my PHP version is 5.6.3. So my question is how can I get the zmq source for PHP API=20131226? Is this available or should I install lower version of PHP. If so which version?

**Comment by Majeh** [comment]
@kirensiva  `phpize` takes care of configuring the "API" of extension, based on PHP you have installed. Therefore, it's not really possible to mess that step up. Are you sure you followed the instructions 100%? Are you sure you moved the .so after building to your extension dir? Are you sure you didn't mess something up with extension path and php.ini and that you have an older version of extension loaded?

**Comment by yumekana** [comment]
I have same issue.
How it was solved ?

**Comment by kirensiva** [comment]
http://windows.php.net/downloads/pecl/releases/zmq/1.1.2/

**Comment by mkoppanen** [comment]
This seems to be resolved
