### ISSUE TITLE
Pub socket doesn't receive messages

### ISSUE THREAD

**Issue by limitium** [mkoppanen/php-zmq#150]
Zmq used libzmq3-dev
I need single endpoint for many publishers

```php
        $endpoint = "inproc://zmq_test";

        $receiver = new \ZMQSocket(self::$context, \ZMQ::SOCKET_SUB);
        $receiver->setSockOpt(\ZMQ::SOCKOPT_SUBSCRIBE, "");
        $receiver->bind($endpoint);

        $sender = new \ZMQSocket(self::$context, \ZMQ::SOCKET_PUB);
        $sender->connect($endpoint);


        $sender->send("a", null);
        echo $receiver->recv();
```
$receiver doesn't get anything. why?

**Comment by phuedx** [comment]
This appears to be a bug with ØMQ. [LIBZMQ-559](https://zeromq.jira.com/browse/LIBZMQ-559) alludes to the SUB socket not being left in the correct state after being bound in the inverted PUBSUB configuration (as in your example).

One workaround, given in [a comment on LIBZMQ-559](https://zeromq.jira.com/browse/LIBZMQ-559?focusedCommentId=19600&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19600), is to poll the SUB socket.

Here's a working version of your example:

```php
$endpoint = "inproc://zmq_test";

$context = new \ZMQContext();

$receiver = new \ZMQSocket($context, \ZMQ::SOCKET_SUB);
$receiver->setSockOpt(\ZMQ::SOCKOPT_SUBSCRIBE, "");
$receiver->bind($endpoint);

$sender = new \ZMQSocket($context, \ZMQ::SOCKET_PUB);
$sender->connect($endpoint);

$poll = new \ZMQPoll();
$poll->add($receiver, \ZMQ::POLL_IN);
$readable = $writable = array();
$poll->poll($readable, $writable, 0); // Timeout immediately.

$sender->send("a", null);
echo $receiver->recv();
```

**Comment by phuedx** [comment]
@limitium What do you think of the example with the workaround in place?

**Comment by limitium** [comment]
Thanks a lot for workaround it fixes example. Now I try to use it in unit tests.
