### ISSUE TITLE
pecl zeromq has not been updated since 2013

### ISSUE THREAD

**Issue by nashadalam** [mkoppanen/php-zmq#151]
Any chance we can expect the update anytime soon. It would be great if it is usable using pecl rather than compiling it. It makes it easier to deployment

**Comment by M1ke** [comment]
With the impending PHP 7 release it might be more worthwhile to look at building for [Pickle](https://github.com/FriendsOfPHP/pickle)

**Comment by mkoppanen** [comment]
Will look at getting PHP7 release out soon

**Comment by pabl0rg** [comment]
Hello!  I'm a few years late to the party.  Is this extensions still being maintained?  Has something else come along that does a better job than 0mq?

**Comment by mkoppanen** [comment]
Hello,

the extension is maintained. Mainly PHP7 related fixes as of late. "something better" highly depends on your use-case

**Comment by mkoppanen** [comment]
I have now merged PHP7 branch to master. It also contains support for PHP5, which is currently frozen and will not receive updates.

I would be grateful if people can test the master branch either against PHP5 or PHP7 and give some feedback so that I can get the ball rolling with release in PECL.

**Comment by M1ke** [comment]
I've just succesfully compiled it on `Ubuntu 14.04` running `PHP 7.0.2-2+deb.sury.org~trusty+1 (cli)` from the ondrej php7 ppa. Running my (known working on PHP5) ZMQ application worked as expected using this new PHP7 version. Running `make test` produced the following. Is there a way to get information on why tests were skipped?

PASS Test send / recv [tests/001-send.phpt] 
PASS Test send / recv binary [tests/002-test-binary.phpt] 
PASS Test getting persistent id [tests/003-getpersistentid.phpt] 
PASS Test getting endpoints [tests/004-getendpoints.phpt] 
PASS Test forcing connect [tests/005-forceconnectarg.phpt] 
PASS Test getsockopt / setsockopt [tests/006-sockopt.phpt] 
PASS Test adding / removing items [tests/007-addremovepoll.phpt] 
PASS Test constructing a socket [tests/008-twowaystoconstruct.phpt] 
PASS Test ispersistent on context and socket [tests/009-ispersistent.phpt] 
PASS Test invalid args for ZMQPoll [tests/010-pollsetinvalidargs.phpt] 
PASS Test exceptions [tests/011-exceptions.phpt] 
PASS Test remove invalid id from ZMQPoll [tests/012-pollsetremoveinvalid.phpt] 
PASS Test clearing and reusing ZMQPoll [tests/013-pollclearandreuse.phpt] 
PASS Test setSockOpt param type [tests/014-setsockoptparam.phpt] 
PASS Test basic callback usage [tests/015-callback.phpt] 
PASS Test invalid args for callback [tests/016-callbackinvalidargs.phpt] 
PASS Test that callback is only called on new socket [tests/017-callbackonlyonnewsocket.phpt] 
PASS Test callback arguments on persistent and non-persistent socket [tests/018-callbackpersistent.phpt] 
PASS Test callback edge-cases [tests/019-callbackinvalidsignature.phpt] 
PASS Test throwing exception from callback [tests/020-exceptionincallback.phpt] 
PASS Test warning in callback [tests/021-callbackwarning.phpt] 
PASS Test that high-watermark works [tests/022-highwatermark.phpt] 
PASS Test that failing callback does not add socket to plist [tests/023-failedcallback.phpt] 
PASS Test retrieving version [tests/024-versionconstant.phpt] 
PASS Test send / recv for multipart messages [tests/025-sendrecvmulti.phpt] 
PASS Test returning socket type [tests/026-sockettype.phpt] 
PASS Test setting and getting values [tests/027-getset.phpt] 
PASS Test send / recv with XPUB and XSUB sockets [tests/028-xpub.phpt] 
PASS Test send / recv with an XREQ and XREP device [tests/029-xrepxreqdevice.phpt] 
SKIP Test send / recv with a manually created XREQ and XREP device [tests/030-xrepmanualqueue.phpt] 
PASS Test last endpoint [tests/031-lastendpoint.phpt] 
PASS Test context options [tests/032-contextopt.phpt] 
PASS Test disconnect [tests/033-disconnect.phpt] 
PASS Test unbind [tests/034-unbind.phpt] 
PASS Test device capture [tests/035-capture.phpt] 
PASS Test device callbacks [tests/036-device.phpt] 
PASS Test device deprecated args [tests/037-device-deprecated.phpt] 
SKIP Test a ZMQCert can be constructed. [tests/038-cert-construct.phpt] 
SKIP Test two ZMQCerts can be tested for equality. [tests/039-cert-equals.phpt] 
SKIP Test a ZMQCert can be cloned. [tests/040-cert-clone.phpt] 
SKIP Test a ZMQCert can get and set metadata. [tests/041-cert-meta.phpt] 
SKIP Test a ZMQCert can be saved. [tests/042-cert-save.phpt] 
SKIP Test a ZMQCert can be loaded. [tests/043-cert-load.phpt] 
SKIP Test a ZMQAuth can be constructed. [tests/044-auth-construct.phpt] 
SKIP Test a ZMQAuth can whitelist or blacklist an IP address. [tests/045-auth-allow-deny.phpt] 
SKIP Test a ZMQCert can be applied to a ZMQSocket. [tests/046-cert-apply.phpt] 
SKIP Test a ZMQAuth can be configured. [tests/047-auth-configure.phpt] 
PASS Test pollset items [tests/048-pollsetitems.phpt] 
PASS Test events [tests/049-events.phpt] 
PASS Test shared context [tests/050-sharedcontext.phpt] 
PASS Test socket count variations [tests/051-socketcount.phpt] 
SKIP Test pthreads integration [tests/052-pthreads.phpt] reason: Requires pthreads extension
PASS Test for GitHub issue 156 (https://github.com/mkoppanen/php-zmq/issues/156) [tests/bug_gh_156.phpt] 
PASS Test for Github issue #165 [tests/bug_gh_165.phpt] 
PASS Test for Github issue #43 [tests/bug_gh_43.phpt] 
PASS Test for Github issue #49 [tests/bug_gh_49.phpt] 
PASS Test for Github issue #50 [tests/bug_gh_50.phpt] 
PASS Test for Github issue #59 [tests/bug_gh_59.phpt] 
PASS Test for Github issue #59 [tests/bug_gh_59_2.phpt]

**Comment by mkoppanen** [comment]
@M1ke,

all the skipped tests looks to be related to CZMQ parts of the extension. I was modernising a lot of parts for PHP7 and noticed that libczmq (notice the extra c there) parts only worked with CZMQ 2 (current is 3).

I'll update the skipif on those tests to give better information.

**Comment by mkoppanen** [comment]
PHP7 release is in pecl, 1.1.3 beta
