### ISSUE TITLE
   Problem 1     - Installation request for react/zmq 0.3.0 -> satisfiable by react/zmq[v0.3.0]

### ISSUE THREAD

**Issue by byggari** [mkoppanen/php-zmq#152]

**Comment by mkoppanen** [comment]
Hello,

react/zmq is a separate project. You should open a ticket with them.

**Comment by bnikola** [comment]
`react/zmq` contains this in its composer.json: 

```
"ext-zmq": "*",
```

That means that the error you're having isn't related to this project nor php extension whatsoever, so you need to take this to the `react/zmq` project.
