### ISSUE TITLE
Closing sockets

### ISSUE THREAD

**Issue by vicaba** [mkoppanen/php-zmq#153]
Is there any way to close ZMQ sockets? ZMQSocket class has not any close() method.

Thanks.

**Comment by mkoppanen** [comment]
What do you mean by close? There is a disconnect method for disconnecting the socket. The actual underlying zeromq socket is destroyed when the object holding it is destroyed (assuming non-persistent scenario).

**Comment by vicaba** [comment]
Thanks, it is working now. I did not found the disconnect method the other day.
