### ISSUE TITLE
Examples not working.

### ISSUE THREAD

**Issue by bweston92** [mkoppanen/php-zmq#163]
I've tried both Windows and Ubuntu operating systems. I've installed the ZMQ extension and `php -m` reports this. How-ever if I start `simple-server.php` and `client.php` yet nothing is happening at all.

Any ideas?

**Comment by phuedx** [comment]
@bweston92: Sorry for not responding sooner. Your seem to have resolved the issue and I was wondering if you could give us some insight as to what it was.

**Comment by bweston92** [comment]
For one the ports where different the `simple-server` was binding to `5555` and client was looking for `5554` but also the types of connections also made it not work. When i changed to `ZMQ::SOCKET_PULL` and `ZMQ::SOCKET_PUSH` it worked fine.
