### ISSUE TITLE
php7 branch: FAIL: Test clearing and reusing ZMQPoll

### ISSUE THREAD

**Issue by zahlprish** [mkoppanen/php-zmq#165]
So I have attempted to install the ZMQ php7 branch on a newly provisioned server with PHP7. I feel like I am pretty close to getting it all set up but am running into a segment fault core dump issue. When I run the "make test" command, it appears only one thing is failing:
FAIL: Test clearing and reusing ZMQPoll [tests/013-pollclearandreuse.phpt]

So I went ahead and investigated this core dump with dbg and come up with:
[full_zmq_test_results.txt](https://github.com/mkoppanen/php-zmq/files/49065/full_zmq_test_results.txt)
[full_backtrace.txt](https://github.com/mkoppanen/php-zmq/files/49067/full_backtrace.txt)
I know the error in my code is coming from this line when I try to run my PHP ZMQ server:
$receiverSocket = $context->getSocket(ZMQ::SOCKET_PULL);

(Note: This all worked perfectly in PHP 5.6)

Any thoughts, comments, potential direction to remedying this would be greatly appreciated!
(full backtrace & zmq test result attached)

Update: I did correct this missing libstdcxx error, but view the attached files for further debugging results. I am just leaving the below as a historical reference.
Program terminated with signal SIGSEGV, Segmentation fault.
#0 php_zmq_fd_cast (stream=, cast_as=, ret=0x7fff68854c9c) at /etc/php-zmq/zmq_fd_stream.c:68
68 if (zmq_getsockopt(intern->socket->z_socket, ZMQ_FD, (int*) ret, &optsiz) != 0) {
Traceback (most recent call last):
File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in
from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'

**Comment by majuca** [comment]
hi, I have the same problem. I modified the file zmq_fd_stream,c at the line 68 like this (add a check on the socket:

```
if (intern->socket && zmq_getsockopt(intern->socket->z_socket, ZMQ_FD, (int*) ret, &optsiz) != 0) {
```

and the segmentation fault is ok but when I have a connection, i have the following error:

[Warning] stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 1024, but you have descriptors numbered at least as high as 32606.
 --enable-fd-setsize=32768 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date. (@line 255 in file /var/www/html/vendor/react/event-loop/StreamSelectLoop.php).
#0 [internal function]: PradoBase::phpErrorHandler(2, 'stream_select()...', '/var/www/html/v...', 255, Array)
#1 /var/www/html/vendor/react/event-loop/StreamSelectLoop.php(255): stream_select(Array, Array, NULL, NULL, NULL)
#2 /var/www/html/vendor/react/event-loop/StreamSelectLoop.php(221): React\EventLoop\StreamSelectLoop->streamSelect(Array, Array, NULL)
#3 /var/www/html/vendor/react/event-loop/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#4 /var/www/html/websocket/server.php(33): React\EventLoop\StreamSelectLoop->run()

My php code:
```
<?php
require dirname(__DIR__) . '/vendor/autoload.php';
require "Pusher.php";

$loop   = React\EventLoop\Factory::create();
$pusher = new Vysual\Pusher;

// Listen for the web server to make a ZeroMQ push after an ajax request
$context = new React\ZMQ\Context($loop);
$pull = $context->getSocket(ZMQ::SOCKET_PULL);
$pull->bind('tcp://127.0.0.1:5555'); // Binding to 127.0.0.1 means the only client that can connect is itself
$pull->on('message', array($pusher, 'onWebSocketEntry'));


// Set up our WebSocket server for clients wanting real-time updates
$webSock = new React\Socket\Server($loop);
$webSock->listen(8888, '0.0.0.0'); // Binding to 0.0.0.0 means remotes can connect
$webServer = new Ratchet\Server\IoServer(
    new Ratchet\Http\HttpServer(
        new Ratchet\WebSocket\WsServer(
            new Ratchet\Wamp\WampServer(
                $pusher
            )
        )
    ),
    $webSock
);


require "loadPrado.php";

$loop->run();
```

**Comment by bweston92** [comment]
@majuca make a PR?

**Comment by mkoppanen** [comment]
So it would seem that intern->socket is NULL at that point? I cannot reproduce this. Which PHP7 version are you running?

**Comment by zprisk** [comment]
I am running PHP 7.0.0RC5 

I can provide ssh access if you want to give me a ssh key to add to the server. It is just a dev/sandbox server waiting on ZMQ.

**Comment by mkoppanen** [comment]
Is it reproducible with php-7.0.1?

**Comment by zprisk** [comment]
I have spun up and provisioned a new server with PHP 7.0.1-5+deb.sury.org~trusty+1 (cli) ( NTS ).

I am getting the same failed test. 

When initially run 'make test' I get the error:
ERROR: Cannot run tests without CLI sapi.

So to get it to run I modify the "Makefile" and change the value:
PHP_EXECUTABLE = NONE
to
PHP_EXECUTABLE = /usr/bin/php7.0

Is this behavior expected? From what I recall when installing on 5.6 I never had to update that value. I am by no means an expert at this level. Am I using the correct PHP_EXECUTABLE value? Anything else I can look into?

**Comment by zprisk** [comment]
[unbuntu-zmq-php7-install.txt](https://github.com/mkoppanen/php-zmq/files/81404/unbuntu-zmq-php7-install.txt)

The attached file is essentially the bash install script that I use to install on my server. I am not sure if it helps anything at all. But since I do not have much experience at this level of development any information I can provide to help solve this can't hurt.

Note: I do not actually run the script in it's entirety, I just run each command step by step ( for now ).

**Comment by M1ke** [comment]
I can confirm that I'm coming across the same problem as @zprisk; I'd have to run through a debugger to  be sure where it segfaults. It runs

    $context = new ZmqContext($loop);
    $pull = $context->getSocket(ZMQ::SOCKET_PULL);
    $pull->bind('tcp://127.0.0.1:5550');

With no problem; my code then enters a React event loop at which point the code segfaults.

**Comment by zprisk** [comment]
@M1ke I just want to add in that I am using React, too. So it sounds like we are in a very similar situation. I attempt to debug that segfault (as you can see from results above), but that is really where my lack of experience comes into play. 

As for the composer dependencies I am using in my application ( just for reference):
		"cboden/ratchet": "0.3.3",
		"react/zmq": "^0.3.0"

**Comment by M1ke** [comment]
Having used xdebug I can see that the script terminates at line 255 in `react/event-loop/StreamSelectLoop.php` where it tries to run `stream_select()` on an array where the first item is the ZMQ stream.

**Comment by mkoppanen** [comment]
Can you test the latest commit? I rewrote the implementation and at least it works in tests. If you have failures please provide something to reproduce with.

**Comment by zprisk** [comment]
@mkoppanen Thanks for the update. I went ahead and spun up a fresh server and reinstalled everything. The update definitely fixed the issue with the one failing test.

I am not sure how much these will help, but:
These are the exact steps I take to install php-zmq & zmq on my servers. I use Laravel's Forge (forge.laravel.com to provision my servers via DigitalOcean).
[php7-unbun-steps.txt](https://github.com/mkoppanen/php-zmq/files/82100/php7-unbun-steps.txt)

This is my actual socket implementation:
[pull-implementation.txt](https://github.com/mkoppanen/php-zmq/files/82101/pull-implementation.txt)

The easiest way would be for you to give me a public key that I could add to my server, in which I can hand over ssh && sudo access. It is a complete throw away / sand box server.

Maybe @M1ke will have better luck with the latest update.

**Comment by mediavariance** [comment]
Thanks for commiting a update so fast! I'm having the same, or at least similar issue. My script seg faults inside of my ratchet loop:
Program received signal SIGSEGV, Segmentation fault.
php_zmq_fd_cast (stream=<optimized out>, cast_as=<optimized out>, ret=0x7fffffffa694) at /opt/php-zmq/zmq_fd_stream.c:68

PHPIZE and ./configure on php-zmq (php7 branch): http://pastebin.com/KUQgS1nr
PHP Code: http://pastebin.com/gkXKGP87

Any ideas?

**Comment by zprisk** [comment]
@mediavariance That is actually the exact segfault I get if you look at the original post in this thread.
```Program terminated with signal SIGSEGV, Segmentation fault.
#0 php_zmq_fd_cast (stream=, cast_as=, ret=0x7fff68854c9c) at /etc/php-zmq/zmq_fd_stream.c:68```

**Comment by mkoppanen** [comment]
@mediavariance How new is your php-zmq?

**Comment by mkoppanen** [comment]
@zprisk can you give me relevant composer.json as well?

**Comment by zprisk** [comment]
@mkoppanen 
This is my composer.json I am using, it is Laravel's stock composer.json and I have added:
		```"laravelcollective/html": "~5.0",
		"guzzlehttp/guzzle": "~6.0",
		"evenement/evenement": "2.0.*",
		"cboden/ratchet": "0.3.3",
		"react/zmq": "^0.3.0"```
[composer.txt](https://github.com/mkoppanen/php-zmq/files/82912/composer.txt)

**Comment by mkoppanen** [comment]
@zprisk,

after following the steps I get the following error:

Fatal error: Uncaught Error: Class 'Swarming\ZMQ\Pusher\Ratchet\GenericSubscriptionPusher' not found in

**Comment by zprisk** [comment]
@mkoppanen Ah, that is my implementation
Add the contents of this zip to the /app directory:
[Swarming.zip](https://github.com/mkoppanen/php-zmq/files/83100/Swarming.zip)

**Comment by zprisk** [comment]
```New connection! (72)```
@mkoppanen Awesome job, man! Thank you for your time working on this. I can confirm that this commit has resolved this segmentation fault issue. Super excited about this, as I have been holding off on my personal project until this got going with PHP7.
