### ISSUE TITLE
PHP Fatal error:  Class 'ZMQAuth' not found

### ISSUE THREAD

**Issue by Kamisama666** [mkoppanen/php-zmq#167]
Hi, I'm trying to get CurveZMQ to work with the php-zmq extension but I keep receiving the same error when I execute the test file : 

**PHP Fatal error:  Class 'ZMQAuth' not found in /tmp/test.php on line 8**

 Where /tmp/test.php contains the exact code from the ironhouse.php example of this repository.

I'm using a newly created Ubuntu 14.04  machine. I've installed the ZeroMQ extension with all it's dependencies (including libsodium) and the php-zmq extension and I've have enabled it in php.ini.
For reference, I have created a gist with the exact commands that I used for the installation process:

https://gist.github.com/Kamisama666/da9ef33b1adf4c6d39ca

After that I try to execute the ironhouse example as I said before and, for some reason I received the above error. I don't know if I'm making some error or if it's something that needs to be fixed in the code.

Thanks in advance.

**Comment by mkoppanen** [comment]
Try running configure with: ./configure --with-czmq

**Comment by Kamisama666** [comment]
I'm still getting the same error. To be clear, the "--with-czmq" argument should be added to the configure of the php-zmq extension, right? That's what I did and the result is the same.

**Comment by mkoppanen** [comment]
Yes, for the php-zmq extension. In the code we check #ifdef HAVE_CZMQ_2

**Comment by Kamisama666** [comment]
Well, as I said, even after doing the whole process but with that argument added, the result is still the same.

**Comment by mkoppanen** [comment]
Do you have czmq installed? Does configure output say anything about czmq? Which version of the extension are you testing with?

**Comment by phuedx** [comment]
Sorry for the late reply all.

@Kamisama666 Could you put both the `configure` command that you're running and the output in a gist?

**Comment by phuedx** [comment]
Mibad. You've provided a link in the description.

**Comment by Kamisama666** [comment]
No worries. The gist that I gave you doesn't have the "--with-czmq" argument, but I did try it with it. As of the output, I will send it to you tomorrow when I get back to work. Thanks for your help and have a good afternoon (or whatever time of the day it's in your time zone).

**Comment by Kamisama666** [comment]
At the end, the problem was that I didn't have czmq installed. After installing it and adding "--with-czmq" to configure, it finally worked. I have updated the gist with the changes. Thanks for all your help. You can consider the issue closed.
