### ISSUE TITLE
Handling kill signals from PHP

### ISSUE THREAD

**Issue by timwhitlock** [mkoppanen/php-zmq#201]
Hi

I've recently started listening for kill signals in some of my long running scripts, but it seems that when PHP is running with `pcntl_async_signals(true)` and a signal occurs during a ZMQ socket operation that a `ZMQSocketException` is thrown from the extension before my own handlers can run. The exceptions all seem to have code `4` but I don't know how specific that is, and the only useful information in the error message is "Interrupted System Call".

Is it possible to get any signal information from the exception, or ask ZMQ to let my handlers run? Failing that, is it safe to assume that any socket exception with code 4 was a kill signal?

Thanks in advance.

**Comment by jankremlacek** [comment]
@timwhitlock, as far as I know, and if I got right what you wrote about, the ZMQ has nothing to do with it. Your app is responsible for handling signals. In the case above, it seems to me ZMQSocketException has been thrown for a different reason than the signal.

It would be easier to get into if you share your exact code. Probably somewhere else as I do not think it's a ZMQ issue.

**Comment by timwhitlock** [comment]
Thanks for the reply.

It's likely I totally misunderstand something, but I can reproduce it.

First, here's how the signal handling works during a normal PHP `sleep()`. Hitting `^C` from the terminal sends an Interrupt and the function handles it.

```php
<?php
// interrupt.php
function handle_interrupt( int $sig, array $info ){
    printf("Received INT signal, exiting gracefully\n");
    exit(0);
}
pcntl_async_signals(true);
pcntl_signal( SIGINT, 'handle_interrupt', false );
printf("Hit ^C in the next 5 seconds\n");
sleep(5);
printf("Too late, exiting with error.\n");
exit(1);
```

Next, here's the clean ZMQ code with no signal handling. This is like the code I've been running for years. Hitting `^C` just kills everything dead, as you'd expect.

```php
<?php
// zmq-clean.php
$listener = new ZMQSocket( new ZMQContext, ZMQ::SOCKET_REP );
$listener->bind('tcp://*:5555');
printf("Hanging on socket, press ^C to exit abruptly\n");
$request = $listener->recvmulti();
printf("You shouldn't see this\n");
exit(1);
```

Finally, here's the two combined where I experience the problem. Hitting `^C` causes the exception to be thrown and the handler is prevented from firing:

```
<?php
// zmq-interrupt.php
function handle_interrupt( int $sig, array $info ){
    printf("Received INT signal, exiting gracefully\n");
    exit(0);
}
pcntl_async_signals(true);
pcntl_signal( SIGINT, 'handle_interrupt', false );

$listener = new ZMQSocket( new ZMQContext, ZMQ::SOCKET_REP );
$listener->bind('tcp://*:5555');
printf("Hanging on socket, press ^C to handle INT signal\n");
try {
    $request = $listener->recvmulti();
}
catch( Throwable $e ){
    printf("%s #%d %s\n", get_class($e), $e->getCode(), $e->getMessage() );
    exit(1);
}
printf("You shouldn't see this\n");
exit(2);
```

The error message I get is `"Failed to receive message: Interrupted system call"`.

**Comment by jankremlacek** [comment]
It's perfectly right behaviour. The `$listener->recvmulti()` synchronously waits for a message, and you exit the app from `handle_interrupt`. So your `exit(0)` raises the Exception as the `$listener->recvmulti()` can not finish its operation.

That's the problem in synchro operations. I would suggest checking for messages on the channel and read them asynchronously, thus in such a case, you will not break yourself.

Check this: https://github.com/friends-of-reactphp/zmq

**Comment by timwhitlock** [comment]
The `exit(0)` doesn't raise the exception, because the handler doesn't actually run. Removing the body of the handler produces the same result. It seems that breaking the synchronous wait to _/attempt/_ calling the handler is what triggers the exception. I understand that this is intened, but it leaves me unable to handle kill signals properly.

As you say this is the correct behaviour I'll close the ticket.
