### ISSUE TITLE
Assert (or segfault or hang) when ZMQ context is created first in parent and after in child

### ISSUE THREAD

**Issue by oldfaust** [mkoppanen/php-zmq#80]
PHP process needs to create context and sockets and later spawns a child with fork, so the child inherits the context.

The child needs its own context acc. to documentation so I create it. 

It fails in different ways like asserts, segfaults or hangs - according to different situations.

What is the proper way to do if you are forced to inherit the parent's context, which is my case?

**Comment by mkoppanen** [comment]
No feedback. Reopen if this surfaces again
